"""telegram binding secret and active-chat partial unique

Revision ID: 1b95143eff9b
Revises: bce695d76e00
Create Date: 2026-08-30 03:23:19.365683

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b95143eff9b"
down_revision: str | None = "bce695d76e00"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Второй фактор доступа бота (ADR-0009). Колонка добавляется nullable, затем
    # заполняется и только потом становится обязательной: `nullable=False` сразу
    # уронил бы миграцию на непустой таблице, а DoD требует применимости и к базе
    # с данными.
    op.add_column(
        "telegram_accounts", sa.Column("secret_hash", sa.String(length=64), nullable=True)
    )

    # Привязки, созданные до появления секрета, аутентифицироваться не могут:
    # секрета у бота для них нет и взяться ему неоткуда. Они помечаются
    # отозванными, а не удаляются (правило 4), и получают заведомо недостижимое
    # значение хеша — пустая строка сюда не годится, иначе `sha256("")` от
    # клиента совпал бы с хранимым. Ручек, создающих такие строки, никогда не
    # существовало, так что на практике цикл не затронет ни одной записи.
    op.execute(
        "UPDATE telegram_accounts "
        "SET secret_hash = md5(random()::text) || md5(random()::text), "
        "    revoked_at = COALESCE(revoked_at, now()) "
        "WHERE secret_hash IS NULL"
    )
    op.alter_column("telegram_accounts", "secret_hash", nullable=False)

    # Уникальность chat_id — только среди живых привязок. Глобальная делала
    # повторную привязку того же чата после отзыва невозможной как новую строку.
    op.drop_constraint(op.f("telegram_accounts_chat_id_key"), "telegram_accounts", type_="unique")
    op.create_index(
        "ix_telegram_accounts_parent_id", "telegram_accounts", ["parent_id"], unique=False
    )
    op.create_index(
        "ix_telegram_accounts_patient_id", "telegram_accounts", ["patient_id"], unique=False
    )
    op.create_index(
        "uq_telegram_accounts_active_chat",
        "telegram_accounts",
        ["chat_id"],
        unique=True,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_telegram_accounts_active_chat",
        table_name="telegram_accounts",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_index("ix_telegram_accounts_patient_id", table_name="telegram_accounts")
    op.drop_index("ix_telegram_accounts_parent_id", table_name="telegram_accounts")
    op.create_unique_constraint(
        op.f("telegram_accounts_chat_id_key"),
        "telegram_accounts",
        ["chat_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("telegram_accounts", "secret_hash")
    # ### end Alembic commands ###
