"""Куски базы знаний помощника

Revision ID: 376f3b526882
Revises: e58859607d91
Create Date: 2026-09-03 17:20:38.038234

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "376f3b526882"
down_revision: str | None = "e58859607d91"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kb_chunks",
        sa.Column("doc_slug", sa.String(length=128), nullable=False),
        sa.Column("doc_title", sa.String(length=255), nullable=False),
        sa.Column("heading_path", sa.String(length=512), nullable=False),
        sa.Column("ord", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("source_path", sa.String(length=512), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "indexed_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "search_tsv",
            postgresql.TSVECTOR(),
            sa.Computed(
                "setweight(to_tsvector('russian', coalesce(doc_title, '')), 'A') || setweight(to_tsvector('russian', coalesce(heading_path, '')), 'B') || setweight(to_tsvector('russian', coalesce(body, '')), 'C')",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doc_slug", "ord", name="uq_kb_chunks_doc_ord"),
    )
    op.create_index(
        "ix_kb_chunks_search", "kb_chunks", ["search_tsv"], unique=False, postgresql_using="gin"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_kb_chunks_search", table_name="kb_chunks", postgresql_using="gin")
    op.drop_table("kb_chunks")
    # ### end Alembic commands ###
