"""drop link codes

Кодов доступа стало два вида: `link_codes` понимал только бот, `access_codes` —
только веб, и семья, пришедшая с приёма с кодом врача, получала в боте
«код недействителен» (ADR-0040, этап Б). Остался один вид.

Таблица удаляется, а не помечается: правило 4 запрещает физическое удаление
КЛИНИЧЕСКИХ данных, а здесь — одноразовые пятнадцатиминутные коды привязки, из
которых ни один не переживает выката. Живые привязки лежат в
`telegram_accounts` и не тронуты: привязанный чат продолжает работать, кода для
этого не нужно.

Откат воссоздаёт пустую таблицу. Вернуть в неё нечего и не нужно: коды в ней
всё равно были бы просрочены.

Revision ID: 600d231323d6
Revises: cca065f2d1a6
Create Date: 2026-09-16 15:19:08.784676

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "600d231323d6"
down_revision: str | None = "cca065f2d1a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("link_codes")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "link_codes",
        sa.Column("code", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("parent_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("patient_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "used_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["users.id"], name=op.f("link_codes_parent_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patients.id"], name=op.f("link_codes_patient_id_fkey")
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("link_codes_pkey")),
    )
    # ### end Alembic commands ###
