"""attachments

Revision ID: 699ac0155e07
Revises: eff24e51f587
Create Date: 2026-08-30 16:47:40.731991

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "699ac0155e07"
down_revision: str | None = "eff24e51f587"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attachments",
        sa.Column(
            "owner_kind", sa.Enum("recipe", "patient", name="attachment_owner_kind"), nullable=False
        ),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("stored_name", sa.String(length=128), nullable=False),
        sa.Column("mime", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=False),
        sa.Column(
            "doc_kind",
            sa.Enum("discharge", "eeg", "lab", "prescription", "other", name="attachment_doc_kind"),
            nullable=True,
        ),
        sa.Column("doc_date", sa.Date(), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stored_name"),
    )
    op.create_index("ix_attachments_owner", "attachments", ["owner_kind", "owner_id"], unique=False)
    op.create_index("ix_attachments_uploaded_by", "attachments", ["uploaded_by"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index("ix_attachments_uploaded_by", table_name="attachments")
    op.drop_index("ix_attachments_owner", table_name="attachments")
    op.drop_table("attachments")

    # Типы-перечисления автогенерация не удаляет: `drop_table` снимает колонки,
    # но сам тип остаётся в схеме, и повторный upgrade падает на «type already
    # exists». Проверка «миграции обратимы» в CI ловит это сразу — образец
    # удаления взят из `901f9beb69ae_report_jobs`.
    op.execute("DROP TYPE IF EXISTS attachment_doc_kind")
    op.execute("DROP TYPE IF EXISTS attachment_owner_kind")
