"""users.totp_last_step and revoked_sessions

Две находки security-прохода от 07.10.2026 (`docs/SECURITY_REVIEW.md`):

- Н8 — код TOTP принимался повторно в окне ±30 с. `users.totp_last_step` —
  номер последнего принятого при входе 30-секундного шага; пусто у тех, кто
  ещё не входил с кодом после ревизии, и это значит «принимается любой шаг».
- Н9 — «Выйти» только снимало cookie. `revoked_sessions` — идентификаторы
  сессий, закрытых выходом, до истечения срока их токена обновления.

Откат удаляет колонку и таблицу: повтор кода и отозванные выходом сессии снова
принимаются до истечения срока токенов.

Revision ID: 835a8cbd4206
Revises: aa3aa11e72c7
Create Date: 2026-10-07

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "835a8cbd4206"
down_revision: str | None = "aa3aa11e72c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "revoked_sessions",
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(
        "ix_revoked_sessions_expires_at", "revoked_sessions", ["expires_at"], unique=False
    )
    op.add_column("users", sa.Column("totp_last_step", sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "totp_last_step")
    op.drop_index("ix_revoked_sessions_expires_at", table_name="revoked_sessions")
    op.drop_table("revoked_sessions")
    # ### end Alembic commands ###
