"""unique product name

Revision ID: 8e85f89b05ba
Revises: e8cd52a223c2
Create Date: 2026-08-28 00:02:31.460374

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e85f89b05ba"
down_revision: str | None = "e8cd52a223c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_products_name_ru_normalized",
        "products",
        [sa.literal_column("lower(btrim(name_ru))")],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_products_name_ru_normalized", table_name="products")
    # ### end Alembic commands ###
