"""attachments purged_at

Отметка «байты сняты с диска». Отдельно от `deleted_at`: между удалением и
уборкой стоит отсрочка (ADR-0013), и без отметки уборщик каждую ночь заново
обходил бы все когда-либо удалённые вложения.

Revision ID: 91800456b812
Revises: 164eaa0d02f9
Create Date: 2026-08-30 22:45:38.651694

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91800456b812"
down_revision: str | None = "164eaa0d02f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attachments", sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("attachments", "purged_at")
    # ### end Alembic commands ###
