"""users totp_pending_secret

Revision ID: e8cd52a223c2
Revises: 05d5a6177f33
Create Date: 2026-08-27 21:41:15.896582

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8cd52a223c2"
down_revision: str | None = "05d5a6177f33"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("totp_pending_secret", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "totp_pending_secret")
    # ### end Alembic commands ###
