"""Коды доступа семьи к ребёнку (ADR-0040).

Карту заводит специалист, а семья получает доступ кодом, который он выдаёт из
карты. Один вид кода на все случаи: первый родитель, второй родитель, ещё один
чат. `link_codes` остаётся на месте — бот переводится на общий код отдельным
этапом, и до тех пор две таблицы живут рядом.

Откат безопасен: таблица новая, ничего, кроме неё, миграция не трогает. Выданные
и погашенные коды при откате исчезнут вместе с журналом выдачи — уже возникшие
привязки `parent_patient` от этого не зависят.

Revision ID: fb62dcddae20
Revises: df3c9cc82858
Create Date: 2026-09-15 17:27:05.053710

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb62dcddae20"
down_revision: str | None = "df3c9cc82858"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_codes",
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("issued_by", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("used_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("used_by", sa.UUID(), nullable=True),
        sa.Column("revoked_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["issued_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["used_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(
        op.f("ix_access_codes_patient_id"), "access_codes", ["patient_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_access_codes_patient_id"), table_name="access_codes")
    op.drop_table("access_codes")
    # ### end Alembic commands ###
