"""Репозитории — единственный слой, обращающийся к БД (раздел 5.1 ТЗ).

В роутерах и сервисах `apps/api` SQL/ORM-запросов быть не должно.
"""

from . import (
    access,
    ai_conversations,
    ai_jobs,
    attachments,
    audit,
    clinical_notes,
    custom_dishes,
    diary,
    dictionaries,
    doctor_summaries,
    intake,
    invitations,
    knowledge_base,
    leads,
    medical_profiles,
    medications,
    menus,
    overview,
    patients,
    prescriptions,
    products,
    recipes,
    report_jobs,
    reports,
    telegram,
    users,
)

__all__ = [
    "access",
    "ai_conversations",
    "ai_jobs",
    "attachments",
    "audit",
    "clinical_notes",
    "custom_dishes",
    "diary",
    "dictionaries",
    "doctor_summaries",
    "intake",
    "invitations",
    "knowledge_base",
    "leads",
    "medical_profiles",
    "medications",
    "menus",
    "overview",
    "patients",
    "prescriptions",
    "products",
    "recipes",
    "report_jobs",
    "reports",
    "telegram",
    "users",
]
